[package]
name = "seshat_cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "seshat"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
diagram_models = { path = "../diagram_models" }
json-patch = "4.1.0"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
petgraph = "0.8.3"
diagram_tool = { version = "0.1.0", path = "../diagram_tool" }

[dev-dependencies]
rstest = "0.18"
proptest = "1.4"
libc = "0.2.183"
tempfile = "3"
im = { version = "15.1.0", features = ["serde"] }
assert_cmd = "2.2.0"
predicates = "3.1.4"
